// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqkqklruuzddckzhdeyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxa3FrbHJ1dXpkZGNremhkZXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDY5ODAsImV4cCI6MjA3MjU4Mjk4MH0.19_jfCLcT7RybvCzUY2Vs1xhnTBIYGFuu2xAjAYgBKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});